/** Mã lỗi của domain AGENT. Chỉ container sở hữu domain này được sửa file. Dạng "AGENT.REASON". */
export const AGENT_ERROR_CODES = [
  // Chat (Direct API)
  "AGENT.API_KEY_MISSING",
  "AGENT.LLM_AUTH_FAILED",
  "AGENT.MODEL_NOT_FOUND",
  "AGENT.LLM_RATE_LIMITED",
  "AGENT.LLM_UNREACHABLE",
  "AGENT.LLM_REQUEST_FAILED",
  "AGENT.INVALID_MESSAGES",
  // CliRunner
  "AGENT.CLI_PROFILE_NOT_FOUND",
  "AGENT.CLI_NOT_INSTALLED",
  "AGENT.CLI_SPEC_CONTEXT_REQUIRED",
  "AGENT.CLI_SPAWN_FAILED",
  "AGENT.CLI_EXIT_NONZERO",
  "AGENT.CLI_TIMEOUT",
  "AGENT.SANDBOX_FAILED",
  "AGENT.RUN_NOT_FOUND",
  "AGENT.RUN_ALREADY_ACTIVE",
] as const;
