/** Mã lỗi của domain CONNECTOR. Chỉ container Connector được sửa file. Dạng "CONNECTOR.REASON". */
export const CONNECTOR_ERROR_CODES = [
  "CONNECTOR.NOT_FOUND",
  "CONNECTOR.NOT_SUPPORTED",
  "CONNECTOR.CLI_NOT_FOUND",
  "CONNECTOR.NEEDS_LOGIN",
  "CONNECTOR.TOKEN_MISSING",
  "CONNECTOR.PROVIDER_ERROR",
  "CONNECTOR.REPO_NOT_FOUND",
  "CONNECTOR.MCP_UNREACHABLE",
  "CONNECTOR.MCP_TOOL_MISSING",
  "CONNECTOR.INVALID_COMMAND",
  "CONNECTOR.INVALID_URL",
  "CONNECTOR.INVALID_SECRET_KEY",
] as const;
