/** Mã lỗi dùng chung cho mọi container. */
export const CORE_ERROR_CODES = [
  "INTERNAL.UNEXPECTED",
  "VALIDATION.FAILED",
  "FIELD.REQUIRED",
  "FIELD.INVALID_FORMAT",
  "FIELD.TOO_SHORT",
  "FIELD.TOO_LONG",
  "FIELD.INVALID_VALUE",
  "REQUEST.MALFORMED_JSON",
  "RESOURCE.NOT_FOUND",
  "RESOURCE.CONFLICT",
] as const;
