/** Mã lỗi của domain FILESYSTEM. Chỉ container FileSystem được sửa file. Dạng "FILESYSTEM.REASON". */
export const FILESYSTEM_ERROR_CODES = ["FILESYSTEM.DIRECTORY_NOT_FOUND", "FILESYSTEM.DIRECTORY_EXISTS", "FILESYSTEM.DIRECTORY_NOT_WRITABLE"] as const;
