/** Mã lỗi của domain STORAGE. Chỉ container sở hữu domain này được sửa file. Dạng "STORAGE.REASON". */
export const STORAGE_ERROR_CODES = [
  "STORAGE.NOT_SUPPORTED",
  "STORAGE.CONFIG_MISSING",
  "STORAGE.PULL_CONFLICT",
  "STORAGE.PUSH_REJECTED",
  "STORAGE.GIT_AUTH_FAILED",
  "STORAGE.GIT_COMMAND_FAILED",
  "STORAGE.CLONE_FAILED",
  "STORAGE.GOOGLE_NOT_CONFIGURED",
  "STORAGE.GOOGLE_AUTH_REQUIRED",
  "STORAGE.GOOGLE_OAUTH_STATE_INVALID",
  "STORAGE.GOOGLE_OAUTH_FAILED",
  "STORAGE.DRIVE_NOT_FOUND",
  "STORAGE.DRIVE_REQUEST_FAILED",
] as const;
